//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("HadronApplication")]
[assembly: System.Reflection.AssemblyDescription("Practice Fusion HadronApplication")]
[assembly: System.Reflection.AssemblyCompany("Practice Fusion")]
[assembly: System.Reflection.AssemblyProduct("HadronApplication")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2007-2015 Practice Fusion")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyVersion("0.13.2.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.13.2.0")]
